HW_Assignment_3/Controllers/HomeController.cs
using HW_Assignment_3.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.EnterpriseServices;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace HW_Assignment_3.Controllers
{
    public class HomeController : Controller
    {
        private LibraryEntities db = new LibraryEntities();

        public async Task<ActionResult> HomeIndex( int? studentsPage, int? booksPage)
        {
            int studentsPageNr = studentsPage ?? 1;
            int booksPageNr = booksPage ?? 1;
            int pageSize = 10;

            var Students = await db.students.ToListAsync();
            var Books = await db.books.Include(b => b.authors).Include(b => b.types).ToListAsync();
            var BookStatusVM = Books.Select(book => new BookStatusVM
            {
                BookS = book,
                Status = GetStatus(book)
            }).ToList();


            var homeVM = new HomeVM()
            {
                Students = Students.ToPagedList(studentsPageNr, pageSize),
                Books = Books.ToPagedList(booksPageNr, pageSize)
            };
            return View(homeVM);
        }
        private string GetStatus(books book)
        {
            var presentDay = DateTime.Today;
            var borrow = book.borrows.FirstOrDefault(b =>
            b.broughtDate == null && b.takenDate <= presentDay);

            return borrow != null ? "Unavailable" : "Availble";
        }

        // GET: students
        public async Task<ActionResult> StudentsIndex()
        {
            return View(await db.students.ToListAsync());
        }

        // GET: students/Details/5
        public async Task<ActionResult> StudentsDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            students students = await db.students.FindAsync(id);
            if (students == null)
            {
                return HttpNotFound();
            }
            return View(students);
        }

        // GET: students/Create
        public ActionResult StudentsCreate()
        {
            return View();
        }

        // POST: students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> StudentsCreate([Bind(Include = "studentId,name,surname,birthdate,gender,class,point")] students students)
        {
            if (ModelState.IsValid)
            {
                db.students.Add(students);
                await db.SaveChangesAsync();
                return RedirectToAction("StudentsIndex");
            }

            return View(students);
        }

        // GET: students/Edit/5
        public async Task<ActionResult> StudentsEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            students students = await db.students.FindAsync(id);
            if (students == null)
            {
                return HttpNotFound();
            }
            return View(students);
        }

        // POST: students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> StudentsEdit([Bind(Include = "studentId,name,surname,birthdate,gender,class,point")] students students)
        {
            if (ModelState.IsValid)
            {
                db.Entry(students).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("StudentsIndex");
            }
            return View(students);
        }

        // GET: students/Delete/5
        public async Task<ActionResult> StudentsDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            students students = await db.students.FindAsync(id);
            if (students == null)
            {
                return HttpNotFound();
            }
            return View(students);
        }

        // POST: students/Delete/5
        [HttpPost, ActionName("StudentsDelete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> StudentsDeleteConfirmed(int id)
        {
            students students = await db.students.FindAsync(id);
            db.students.Remove(students);
            await db.SaveChangesAsync();
            return RedirectToAction("StudentsIndex");
        }

        // GET: books
        public async Task<ActionResult> BooksIndex()
        {
            var books = db.books.Include(b => b.authors).Include(b => b.types);
            return View(await books.ToListAsync());
        }

        // GET: books/Details/5
        public async Task<ActionResult> BooksDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // GET: books/Create
        public ActionResult BooksCreate()
        {
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name");
            ViewBag.typeId = new SelectList(db.types, "typeId", "name");
            return View();
        }

        // POST: books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> BooksCreate([Bind(Include = "bookId,name,pagecount,point,authorId,typeId")] books books)
        {
            if (ModelState.IsValid)
            {
                db.books.Add(books);
                await db.SaveChangesAsync();
                return RedirectToAction("BooksIndex");
            }

            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // GET: books/Edit/5
        public async Task<ActionResult> BooksEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // POST: books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> BooksEdit([Bind(Include = "bookId,name,pagecount,point,authorId,typeId")] books books)
        {
            if (ModelState.IsValid)
            {
                db.Entry(books).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("BooksIndex");
            }
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // GET: books/Delete/5
        public async Task<ActionResult> BooksDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // POST: books/Delete/5
        [HttpPost, ActionName("BooksDelete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> BooksDeleteConfirmed(int id)
        {
            books books = await db.books.FindAsync(id);
            db.books.Remove(books);
            await db.SaveChangesAsync();
            return RedirectToAction("BooksIndex");
        }







        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

HW_Assignment_3/Controllers/booksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HW_Assignment_3.Models;

namespace HW_Assignment_3.Controllers
{
    public class booksController : Controller
    {
        private LibraryEntities db = new LibraryEntities();

        // GET: books
        public async Task<ActionResult> Index()
        {
            var books = db.books.Include(b => b.authors).Include(b => b.types);
            return View(await books.ToListAsync());
        }

        // GET: books/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // GET: books/Create
        public ActionResult Create()
        {
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name");
            ViewBag.typeId = new SelectList(db.types, "typeId", "name");
            return View();
        }

        // POST: books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "bookId,name,pagecount,point,authorId,typeId")] books books)
        {
            if (ModelState.IsValid)
            {
                db.books.Add(books);
                await db.SaveChangesAsync();
                return RedirectToAction("HomeIndex", "Home");
            }

            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // GET: books/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // POST: books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "bookId,name,pagecount,point,authorId,typeId")] books books)
        {
            if (ModelState.IsValid)
            {
                db.Entry(books).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("HomeIndex", "Home");
            }
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // GET: books/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // POST: books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            books books = await db.books.FindAsync(id);
            db.books.Remove(books);
            await db.SaveChangesAsync();
            return RedirectToAction("HomeIndex", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HW_Assignment_3/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

HW_Assignment_3/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

HW_Assignment_3/Views/Home/HomeIndex.cshtml
@model HW_Assignment_3.Models.HomeVM
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-latest.ja"></script>


@{
	ViewBag.Title = "HomeIndex";
}

@using PagedList.Mvc
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<style>
	body {
		background-image: url('../Content/MyStyle/Home.jpeg');
		background-size: inherit;
	}

	.ul.pagination {
		display: inline-block;
		padding: 0;
		margin: 0;
	}

	ul.pagination li {
		display: inline;
	}

	ul.pagination li a {
		color: black;
		float: left;
		padding: 8px 16px;
		text-decoration: none;
		transition: background-color .3s;
	
	}

	ul.pagination li a.active {
		background-color: #4CAF50;
		color: white;
	}

	ul.pagination li a:hover:not(.active) {
		background-color: #ddd;
	}

	* {
		box-sizing: border-box;
	}

	.row {
		display: flex;
	}

	.column {
		flex: 50%;
		padding: 5px;
	}
	h2 {
		color: white;
	}


</style>

<body>
	<div class="row">
		<div class="column">
			<div class="d-flex">
				<div class="flex-fill">
					<h2>Students</h2>

					<p>
						<button type="button" class="btn btn-info create-link" data-url="@Url.Action("Create", "students")">
							Create Student
						</button>
						@*<a href="#" class=" btn btn-md-primary create-link" data-url="@Url.Action("Create", "ToDoLists")">Create New Sample Entity</a>*@
					</p>

					<table class="table table-striped table-bordered" style="width:100%; border-collapse: collapse">
						<tr>
							<th>
								Name
							</th>
							<th>
								Surname
							</th>
							<th>
								Birthdate
							</th>
							<th>
								Gender
							</th>
							<th>
								Class
							</th>
							<th>
								Point
							</th>
							@*<th>
									CRUD Buttons
								</th>*@

						</tr>
						@foreach (var item in Model.Students)
						{
							<tr style="border-collapse: collapse">
								<td>
									@Html.DisplayFor(modelItem => item.name)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.surname)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.birthdate)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.gender)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.@class)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.point)
								</td>

								@*<td class="text-end">
										 Add text-end class here
										<a href="#" class="btn btn-secondary edit-link" data-url="@Url.Action("Edit", "students", new { id = item.studentId })">Edit</a>
										<a href="#" class="btn btn-secondary details-link" data-url="@Url.Action("Details", "students", new { id = item.studentId })">Details</a>
										<a href="#" class="btn btn-secondary delete-link" data-url="@Url.Action("Delete", "students", new { id = item.studentId })">Delete</a>
									</td>*@
							</tr>
						}
					</table>
					<div class="pagination" style="background-color: white">
						@Html.PagedListPager(Model.Students, page => Url.Action("HomeIndex", new { studentsPage = page }))
					</div>
				</div>
			</div>
			<div class="row">
				<div class="column">
					<div class="d-flex">
						<div class="flex-fill">
							<h2>Books</h2>

							<p>
								<button type="button" class="btn btn-info create-lookup-link" data-url="@Url.Action("Create", "books")">
									Create Book
								</button>
								@*<a href="#" class="create-lookup-link" data-url="@Url.Action("Create", "ListItems")">Create New Sample LookUp</a>*@
							</p>

							<table class="table table-striped table-bordered" style="width: 100%; border-collapse: collapse">
								<tr>
									<th>
										Name
									</th>
									<th>
										Page Count
									</th>
									<th>
										Point
									</th>
									<th>
										Author
									</th>
									<th>
										Type
									</th>
									@*<th>
											CRUD Buttons
										</th>*@
									<th>
										Status
									</th>
								</tr>
								@foreach (var item in Model.Books)
								{
									<tr>
										<td>
											@Html.DisplayFor(modelItem => item.name)
										</td>
										<td>
											@Html.DisplayFor(modelItem => item.pagecount)
										</td>
										<td>
											@Html.DisplayFor(modelItem => item.point)
										</td>
										<td>
											@Html.DisplayFor(modelItem => item.authors.name)
										</td>
										<td>
											@Html.DisplayFor(modelItem => item.types.name)
										</td>
										@*<td class="text-end">
												 Add text-end class here
												<a href="#" class="btn btn-secondary edit-link" data-url="@Url.Action("Edit", "books", new { id = item.bookId })">Edit</a>
												<a href="#" class="btn btn-secondary details-link" data-url="@Url.Action("Details", "books", new { id = item.bookId })">Details</a>
												<a href="#" class="btn btn-secondary delete-link" data-url="@Url.Action("Delete", "books", new { id = item.bookId })">Delete</a>
											</td>*@
										<td>
											@{
												var presentDay = DateTime.Today;
												var borrow = item.borrows.FirstOrDefault(b =>
												b.takenDate <= presentDay &&
												(b.broughtDate == null || b.broughtDate > presentDay));
												var status = (borrow != null) ? "Unavailable" : "Available";
												@status
											}

										</td>
									</tr>
								}
							</table>
							<div class="pagination" style="background-color: white">
								@Html.PagedListPager(Model.Books, page => Url.Action("HomeIndex", new { booksPage = page }))
							</div>
						</div>
					</div>
				</div>
			</div>

			<div id="myModal" class="modal fade" tabindex="-1">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<h5 class="modal-title">Sample Async CRUD</h5>
							<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
						</div>
						<div class="modal-body" id="modal-content">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>

<script>
	$(function () {
		// Function to handle Edit link click event in the Combined View and Details modal
		$(".edit-link, .edit-link-in-modal").click(function (e) {
			e.preventDefault();
			var url = $(this).data("url");

			$.get(url, function (data) {
				$("#modal-content").empty();
				$("#modal-content").html(data);
				$("#myModal").modal("show");
			});
		});

		// Function to handle form submission within the modal
		$("#modal-content").on("submit", "form", function (e) {
			e.preventDefault();
			var form = $(this);
			var url = form.attr("action");
			var formData = form.serialize();

			$.post(url, formData, function (data) {
				$("#myModal").modal("hide");
				location.reload();
			});
		});

		// Function to handle other links (details, delete, create) within the modal
		$(".details-link, .delete-link, .create-link, .create-lookup-link").click(function (e) {
			e.preventDefault();
			var url = $(this).data("url");

			$.get(url, function (data) {
				$("#modal-content").empty();
				$("#modal-content").html(data);
				$("#myModal").modal("show");
			});
		});
	});
</script>

HW_Assignment_3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>